//! `forge init` — scaffold a new Reticulum network project.
//!
//! # Security
//! - Project name is sanitized: blocks path traversal, shell metacharacters, control chars.
//! - Topology is validated against allowed types before use.
//! - Subdirectory creation is bounded within the project root.
//! - File writes use restrictive permissions (0o644).

use crate::config::ForgeConfig;
use crate::error::{ForgeError, ForgeResult};
use console::style;
use indicatif::{ProgressBar, ProgressStyle};
use std::path::PathBuf;

/// Maximum project name length.
const MAX_NAME_LENGTH: usize = 128;

/// Valid topology types for init.
const VALID_TOPOLOGIES: &[&str] = &["mesh", "star", "ring", "chain", "custom"];

/// Create a new Reticulum network project at `./<name>`.
pub fn execute(name: &str, topology: &str) -> ForgeResult<()> {
    // ---- validate project name ----
    let safe_name = sanitize_project_name(name)?;

    // ---- validate topology ----
    let topo = topology.trim().to_lowercase();
    if !VALID_TOPOLOGIES.contains(&topo.as_str()) {
        return Err(ForgeError::Validation(format!(
            "unsupported topology '{}'. Valid: {}",
            topology,
            VALID_TOPOLOGIES.join(", ")
        )));
    }

    let project_dir = PathBuf::from(&safe_name);

    // --- progress spinner ---
    let pb = ProgressBar::new(4);
    pb.set_style(
        ProgressStyle::default_spinner()
            .template("{spinner:.green} {msg}")
            .expect("static template is valid")
            .tick_strings(&[
                "▹▹▹▹▹",
                "▸▹▹▹▹",
                "▹▸▹▹▹",
                "▹▹▸▹▹",
                "▹▹▹▸▹",
                "▹▹▹▹▸",
                "▪▪▪▪▪",
            ]),
    );

    // 1. Create project root
    pb.set_message(format!("Creating project '{}'...", safe_name));
    std::fs::create_dir_all(&project_dir).map_err(crate::error::ForgeError::Io)?;
    pb.inc(1);

    // 2. Create subdirectory structure
    pb.set_message("Creating directory structure...");
    for sub in &["nodes", "interfaces", "deploy"] {
        std::fs::create_dir_all(project_dir.join(sub)).map_err(crate::error::ForgeError::Io)?;
    }
    pb.inc(1);

    // 3. Generate forge.toml with restrictive permissions
    pb.set_message("Generating forge.toml...");
    let config = ForgeConfig::default_template(&safe_name, &topo);
    let toml_str = config.to_toml_string()?;
    let forge_toml_path = project_dir.join("forge.toml");
    std::fs::write(&forge_toml_path, &toml_str).map_err(crate::error::ForgeError::Io)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&forge_toml_path, std::fs::Permissions::from_mode(0o644))
            .map_err(crate::error::ForgeError::Io)?;
    }
    pb.inc(1);

    // 4. Generate default interface template
    pb.set_message("Generating default interface template...");
    let default_iface_content = format!(
        r#"# Default AutoInterface for {name}
# Generated by Reticulum Forge

[interfaces]
  [interfaces.auto_interface_0]
  type = AutoInterface
  interface_enabled = yes
  outgoing = yes
  group_id = "forge_default"
  group_port = 42671
  discovery_interval = 60
"#,
        name = safe_name
    );
    let default_iface_path = project_dir.join("interfaces").join("default.config");
    std::fs::write(&default_iface_path, &default_iface_content)
        .map_err(crate::error::ForgeError::Io)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&default_iface_path, std::fs::Permissions::from_mode(0o644))
            .map_err(crate::error::ForgeError::Io)?;
    }
    pb.inc(1);

    pb.finish_with_message(format!(
        "{} Project '{}' created successfully!",
        style("✔").green(),
        safe_name
    ));

    // Print summary
    println!("  {} {}", style("📁").bold(), project_dir.display());
    println!("  {} Project configuration", style("├── forge.toml").dim());
    println!("  {} Node definitions", style("├── nodes/").dim());
    println!(
        "  {} Interface configurations",
        style("├── interfaces/").dim()
    );
    println!(
        "  {} Default interface template",
        style("│   └── default.config").dim()
    );
    println!("  {} Deployment manifests", style("└── deploy/").dim());

    Ok(())
}

/// Sanitize a project name: block path traversal, shell injection, and control characters.
fn sanitize_project_name(name: &str) -> ForgeResult<String> {
    let trimmed = name.trim();

    if trimmed.is_empty() {
        return Err(ForgeError::Validation(
            "project name must not be empty".into(),
        ));
    }

    if trimmed.len() > MAX_NAME_LENGTH {
        return Err(ForgeError::Validation(format!(
            "project name must be {} characters or fewer",
            MAX_NAME_LENGTH
        )));
    }

    // Block path traversal
    if trimmed.contains("..") {
        return Err(ForgeError::Validation(
            "project name must not contain '..' (directory traversal)".into(),
        ));
    }

    // Block path separators
    if trimmed.contains('/') || trimmed.contains('\\') {
        return Err(ForgeError::Validation(
            "project name must not contain path separators".into(),
        ));
    }

    // Block control characters
    if trimmed.contains(|c: char| c.is_ascii_control()) {
        return Err(ForgeError::Validation(
            "project name must not contain control characters".into(),
        ));
    }

    Ok(trimmed.to_string())
}
