//! Template engine wrapper for Reticulum config generation.
//!
//! # Security
//! - All templates are embedded (no filesystem loading) — prevents template injection via file path.
//! - Tera auto-escapes output by default — prevents injection through rendered values.
//! - Template names are validated against a known set — no arbitrary template lookups.

use crate::error::{ForgeError, ForgeResult};
use std::collections::HashMap;
use tera::{Context, Tera};

/// Embedded forge.toml template for `forge init`.
const FORGE_TOML_TEMPLATE: &str = r#"
[project]
name = "{{ project_name }}"
version = "1.0.0"
description = "{{ description }}"
topology = "{{ topology }}"

[network]
default_interface = ""
transport = "udp"
"#;

/// Generic Reticulum interface config template (used by `forge init` default).
const RETICULUM_CONFIG_TEMPLATE: &str = r#"
# Reticulum interface configuration
# Generated by Reticulum Forge

[reticulum]

[logging]
level = "info"

[interfaces]
  [interfaces.{{ interface_name }}]
  type = "{{ interface_type }}"
{% for key, value in params %}
  {{ key }} = "{{ value }}"
{% endfor %}
"#;

/// RNode LoRa interface template.
const RNODE_CONFIG_TEMPLATE: &str = r#"
# RNode LoRa interface — {{ interface_name }}
# Generated by Reticulum Forge

[interfaces]
  [interfaces.{{ interface_name }}]
  type = RNodeInterface
  interface_enabled = yes
  outgoing = yes
  port = /dev/{{ port }}
  frequency = {{ freq_hz }}
  bandwidth = {{ bw_hz }}
  txpower = {{ tx_power }}
  spreadingfactor = {{ sf }}
  codingrate = {{ coding_rate }}
"#;

/// Serial TNC / KISS interface template.
const SERIAL_CONFIG_TEMPLATE: &str = r#"
# Serial TNC interface — {{ interface_name }}
# Generated by Reticulum Forge

[interfaces]
  [interfaces.{{ interface_name }}]
  type = SerialInterface
  interface_enabled = yes
  outgoing = yes
  port = /dev/{{ port }}
  baudrate = {{ baud }}
{% if flow_control != "none" %}
  flow_control = {{ flow_control }}
{% endif %}
"#;

/// TCP client interface template.
const TCP_CLIENT_CONFIG_TEMPLATE: &str = r#"
# TCP client interface — {{ interface_name }}
# Generated by Reticulum Forge

[interfaces]
  [interfaces.{{ interface_name }}]
  type = TCPClientInterface
  interface_enabled = yes
  target_host = "{{ target_host }}"
  target_port = {{ target_port }}
  keepalive = {{ keepalive }}
{% if timeout %}
  timeout = {{ timeout }}
{% endif %}
"#;

/// TCP server interface template.
const TCP_SERVER_CONFIG_TEMPLATE: &str = r#"
# TCP server interface — {{ interface_name }}
# Generated by Reticulum Forge

[interfaces]
  [interfaces.{{ interface_name }}]
  type = TCPServerInterface
  interface_enabled = yes
  listen = {{ listen_address }}:{{ listen_port }}
{% if allowed_hosts %}
  allowed_networks = {{ allowed_hosts }}
{% endif %}
{% if require_encryption == "yes" %}
  require_encryption = yes
{% endif %}
"#;

/// AutoInterface (local peer discovery) template.
const AUTO_INTERFACE_CONFIG_TEMPLATE: &str = r#"
# AutoInterface — {{ interface_name }}
# Generated by Reticulum Forge

[interfaces]
  [interfaces.{{ interface_name }}]
  type = AutoInterface
  interface_enabled = yes
  group_id = "{{ group_id }}"
  group_port = {{ group_port }}
  discovery_interval = {{ discovery_interval }}
{% if multicast_address %}
  multicast_address = "{{ multicast_address }}"
{% endif %}
"#;

const NODE_TEMPLATE: &str = r#"
# Node definition: {{ node_name }}
# Interfaces: {{ interfaces }}

[node]
identity_file = "{{ node_name }}.identity"
enabled = true

[interfaces]
# Add interface references here
"#;

/// Wraps Tera for rendering template-based configs.
pub struct TemplateEngine {
    tera: Tera,
}

impl TemplateEngine {
    /// Create a new engine with all built-in templates registered.
    ///
    /// # Security
    /// All templates are embedded at compile time via `const` strings.
    /// No templates are loaded from the filesystem, preventing path traversal
    /// or injection attacks through template loading.
    pub fn new() -> ForgeResult<Self> {
        let mut tera = Tera::default();

        let templates: &[(&str, &str)] = &[
            ("forge_toml", FORGE_TOML_TEMPLATE),
            ("reticulum_config", RETICULUM_CONFIG_TEMPLATE),
            ("rnode_config", RNODE_CONFIG_TEMPLATE),
            ("serial_config", SERIAL_CONFIG_TEMPLATE),
            ("tcp_client_config", TCP_CLIENT_CONFIG_TEMPLATE),
            ("tcp_server_config", TCP_SERVER_CONFIG_TEMPLATE),
            ("auto_interface_config", AUTO_INTERFACE_CONFIG_TEMPLATE),
            ("node_template", NODE_TEMPLATE),
        ];

        for (name, content) in templates {
            tera.add_raw_template(name, content)
                .map_err(|e| ForgeError::TeraInit(format!("failed to register {name}: {e}")))?;
        }

        Ok(TemplateEngine { tera })
    }

    /// Render a named template with the given Tera context.
    ///
    /// Returns an error if the template name doesn't match a registered template
    /// (preventing arbitrary template lookups).
    pub fn render(&self, template_name: &str, context: &Context) -> ForgeResult<String> {
        self.tera
            .render(template_name, context)
            .map_err(ForgeError::Template)
    }

    /// Convenience: render a template using a string-keyed map.
    pub fn render_map(
        &self,
        template_name: &str,
        vars: &HashMap<&str, &str>,
    ) -> ForgeResult<String> {
        let ctx = Context::from_serialize(vars)
            .map_err(|e| ForgeError::Template(tera::Error::msg(format!("context error: {e}"))))?;
        self.render(template_name, &ctx)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_render_forge_toml() {
        let engine = TemplateEngine::new().unwrap();
        let mut vars = HashMap::new();
        vars.insert("project_name", "my-net");
        vars.insert("description", "test project");
        vars.insert("topology", "mesh");

        let result = engine.render_map("forge_toml", &vars).unwrap();
        assert!(result.contains("my-net"));
        assert!(result.contains("mesh"));
    }

    #[test]
    fn test_render_rnode_config() {
        let engine = TemplateEngine::new().unwrap();
        let mut vars = HashMap::new();
        vars.insert("interface_name", "lora_0");
        vars.insert("port", "ttyUSB0");
        vars.insert("freq_hz", "868000000");
        vars.insert("bw_hz", "125000");
        vars.insert("tx_power", "17");
        vars.insert("sf", "10");
        vars.insert("coding_rate", "6");

        let result = engine.render_map("rnode_config", &vars).unwrap();
        assert!(result.contains("868000000"));
        assert!(result.contains("RNodeInterface"));
        assert!(result.contains("ttyUSB0"));
    }

    #[test]
    fn test_render_tcp_client() {
        let engine = TemplateEngine::new().unwrap();
        let mut vars = HashMap::new();
        vars.insert("interface_name", "internet_0");
        vars.insert("target_host", "peer.reticulum.network");
        vars.insert("target_port", "37428");
        vars.insert("keepalive", "300");

        let result = engine.render_map("tcp_client_config", &vars).unwrap();
        assert!(result.contains("peer.reticulum.network"));
        assert!(result.contains("37428"));
        assert!(result.contains("TCPClientInterface"));
    }

    #[test]
    fn test_render_unknown_template() {
        let engine = TemplateEngine::new().unwrap();
        let ctx = Context::new();
        assert!(engine.render("nonexistent", &ctx).is_err());
    }
}
